FROM jenkins/jenkins:lts
# if we want to install via apt
USER root
RUN apt-get update && apt-get install -y ruby make python3 python3-pip
# drop back to the regular jenkins user - good practice
USER jenkins
